package com.isha.quizapp.dao;

import com.isha.quizapp.Question;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Repository;

import java.util.List;

// We extend JpaRepository because:
// saves time
// no SQL needed
// no implementation needed
// Spring handles everything


// Question → Entity class
// Integer → Primary key type

@Repository
public interface QuestionDao extends JpaRepository<Question,Integer>
{
    // This is called DERIVED Query Method
    // now here we had to create a method for this
    // but as we are having a separate column as category
    // so we simply tell JPA find by category so it is smart enough to understand
    //  SQL generated by spring here : SELECT * FROM question WHERE category = ?;
    // but if we are having something like more complex ones then
    // we need to use HQL hibernate query language
    // or JPQL
  List<Question> findByCategory(String category);

}
